# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd857d8cb308a2da11e799bd2af1d99069204a8a3a28d52c4122c38a585d2b315aca637701169e5b3e8d382f246f85c1c066099e0d61defc12f9a45477ef0e22

test:
  secret_key_base: 7db9205c2bf703260aa0edbd99856520dee031fc8091c8c21082845dbed1436edb6ed9eedce0013e352abb577d6d41ea4c507c088a280963e2af5a209be2202d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
